using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameOverSammlung : MonoBehaviour
{
    public string[] GameOver = new string[]
    {
        "Game Over",
        "You died.",
        "You died.",
        "Why did you do that?",
        "You died",
        "You are so dead.",
        //DIE ERSTEN SECHS WERDEN IN REIHENFOLGE ABGESPIELT
        "You died.",
        "You died. Again.",
        "You died.",
        "You died.",
        "Wow.",
        "Really? Again?",
        "Nice, now you're dead.",
        "There you go again.",
        "Well done. Not.",
        "You are really dead.",
        "Dead.",
        "O_O",
        "<3",
        "You left this place.",
        "You passed away.",
        "You is no more.",
        "You is belong to Death",
        "So much die.",
        "Dat die.",
        ":/",
        "That was funny :D",
        "Oh, you died again!",
        "There you go again.",
        "Okay, honestly. What's wrong?",
        "AFK?",
        "Well done.",
        "Pff, wow.",
        "Damn.",
        "Meh.",
        "Try Again.",
        "You Lose.",
        "Your Life is over.",
        "You will be remembered.",
        "Gone to soon.",
        "Get well soon :)",
        "Tzzz.",
        "That was sad.",
        "That‘s so sad.",
        "Dad i‘m sad.",
        "Ouchie!",
        "Uuuuh, did it hurt?",
        "Stand Up!",
        "Don't quit now.",
        "Meet your Maker",
        "Greet the Reaper!",
        "People die when they are killed...",
        "R.I.P.",
        "Your constant dying amuses me.",
        "Shit, i forgot the Popcorn.",
        "Laaame!",
        "WASTED!, " +
        ";D",
        "Dude, really?",
        "Well...",
        "At least you tried.",
        "Hasta la vista Baby!",
        "Owned.",
        "Well, what can i say?",
        "Better luck next time!",
        "The cake is a lie.",
        "Press F to pay respects.",
        "There is no spoon.",
        "rekt.",
        "git gud.",
        "You were winning, until you lost.",
        "Oopsie Woopsie!",
        "Ok, this was epic.",
        "You transformed into Lasagna.",
        "Ragequit?",
        "There is no Cow Level.",
        "I II II IL",
        "Yikes.",
        "#deep",
        "You are in a better place now.",
        "afsdflkja#*!!",
        "That was super effective!",
        "Keep trying!",
        "Such dead.",
        "So much gone.",
        "Game over.",
        "I guess you won't be missed, huh?",
        "Awesome!",
    };



}
